name: CI - Windows
on: [pull_request, push]

jobs:
  build:
    name: 🚧Build
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: '🧰 Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: '📥 Install dependencies'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >
          mingw-w64-x86_64-qt5-static
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-gcc

    - name: '🚧 Build package'
      run: |
        cmake \
          -B build \
          -G "Ninja" \
          -DCMAKE_PREFIX_PATH=/mingw64/qt5-static \
          -DLINK_SEARCH_START_STATIC=ON \
          -DCMAKE_EXE_LINKER_FLAGS="-static -static-libgcc -static-libstdc++"
        cmake --build build

    - name: '📤 upload package'
      uses: actions/upload-artifact@v2
      with:
        name: built-artifacts
        path: build/*.exe
